- name: Get status
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    - include_tasks: "{{ playbook_dir }}/../tasks/get_device_info.yaml"
      vars:
        device_info_file: "{{ (playbook_dir + '/../.output/pre-upgrade-device-info-' + timestamp + '.json') | realpath }}"
