# To try this playbook, run
#
#   ansible-playbook -i inventory/inventory.ini playbooks/python_wrapper.yaml
#
# You should see a file '<project_root>/output/test.json.tmp' with the following contents
#   {
#     "input_args": [
#       "bigip.local",
#       "username",
#       "password"
#     ]
#   }
#
- name: Python wrapper
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute Python script locally on machine where Ansible is run
      command: "python3 {{ playbook_dir }}/../scripts/ansible-wrapper-test.py bigip.local username password"
      delegate_to: localhost
      run_once: true
      register: script_output

    - name: Convert Python script output (AnsibleUnsafeText) into Ansible dict
      set_fact:
        json_output: "{{ script_output.stdout_lines[0] }}"

    - name: Write Python script output to a file locally
      copy:
        dest: "{{ playbook_dir }}/../.output/test.json.tmp"
        content: "{{ json_output | to_nice_json(indent=2) }}"
      delegate_to: localhost
